apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  ## example with an istio local ratelimit
  - httpbin-local-ratelimit
  ## example with a global ratelimit
  - httpbin-global-ratelimit
