apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  ## base resources for httpbin service
  - namespace.yaml
  - httpbin.yaml
  - virtual-service.yaml
  - gateway.yaml
  ## Envoy ratelimit service deployment
  - rt-cm.yaml
  - rt-service.yaml
  ## Enable Gateway filter chain for global rate limit service
  - rt-global-enable.yaml
  - rt-httpbin-rate-limit.yaml
