apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: httpbin-global-ratelimit
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: PATH
        value: "/headers"
        descriptors:
          - key: custom_header
            value: "*"
            rate_limit:
              unit: minute
              requests_per_unit: 10
          - key: client_cert_header
            value: "*"
            rate_limit:
              unit: minute
              requests_per_unit: 10
      - key: DESCRIPTOR_TEST
        value: "*"
        rate_limit:
          unit: minute
          requests_per_unit: 10
